name: Jest Test

on:
  push

jobs:
  jest:
    name: Executar os testes do Jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm install -D
      - run: npm test
